### ISSUE TITLE
[FEAT] Julia wrapper?

### ISSUE THREAD

**Issue by dforero0896** [MikeSWang/Triumvirate#27]
Hi, since the library seems to be build in C++ primarily with a python interface. I wonder how difficult it would be to write a thin wrapper for Julia. Julia supports C function calls natively so in principle having a shared library with functions that accept, for example, `bispec(real *posx, real *posy, real *posz)` should be enough.

I can look into it at some point but I am not familiar with the library so it will be harder.

Thanks in advance!

**Comment by MikeSWang** [comment]
Hi Daniel, thanks for the interesting suggestion. I am not an experienced Julia developer, but a quick Google seems to confirm that it has decent support for C++ interface.

The current algorithms have quite a few custom classes (for the catalogues, parameter set etc) as input parameters, so all of these need to be wrapped in/interfaced with Julia too. It will likely still take a long time for me... I will leave this issue open for now in case it gathers a lot of interest from Julia users, in which case it may warrant more immediate efforts.
